-- V12: Multi-college tenants - colleges table + additive backfill
-- Creates the colleges tenant table, adds a nullable college_id column to the
-- legacy data tables (departments / faculty / users), creates ROLE_COLLEGE_ADMIN
-- and grants it to every existing platform admin, and backfills all pre-existing
-- rows into a single default tenant (DEV001). Strictly additive: no row is
-- modified beyond assigning a tenant, nothing is deleted or reset.

CREATE TABLE IF NOT EXISTS colleges (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(255) NOT NULL,
    code       VARCHAR(50)  NOT NULL UNIQUE,
    address    TEXT,
    phone      VARCHAR(20),
    email      VARCHAR(255),
    is_active  BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE,
    created_by VARCHAR(100),
    updated_by VARCHAR(100)
);

CREATE INDEX IF NOT EXISTS idx_colleges_code ON colleges (code);

-- ROLE_COLLEGE_ADMIN role (the DataInitializer seed is idempotent, but the role
-- must exist here so the backfill grant below resolves it on Postgres).
INSERT INTO roles (name, description)
SELECT 'ROLE_COLLEGE_ADMIN', 'College Administrator'
WHERE NOT EXISTS (SELECT 1 FROM roles WHERE name = 'ROLE_COLLEGE_ADMIN');

-- Tenant columns (nullable; pre-existing rows are backfilled below).
ALTER TABLE departments ADD COLUMN IF NOT EXISTS college_id BIGINT DEFAULT NULL REFERENCES colleges(id);
ALTER TABLE faculty      ADD COLUMN IF NOT EXISTS college_id BIGINT DEFAULT NULL REFERENCES colleges(id);
ALTER TABLE users        ADD COLUMN IF NOT EXISTS college_id BIGINT DEFAULT NULL REFERENCES colleges(id);

-- Default tenant, named after the legacy single-row institution (id = 1).
INSERT INTO colleges (id, name, address, code)
SELECT 1,
       COALESCE((SELECT name FROM institution WHERE id = 1), 'Default College'),
       (SELECT address FROM institution WHERE id = 1),
       'DEV001'
WHERE NOT EXISTS (SELECT 1 FROM colleges WHERE code = 'DEV001');

-- Explicit id=1 above does not advance the identity sequence; re-align it so
-- the next tenant gets id=2.
SELECT setval(pg_get_serial_sequence('colleges', 'id'), (SELECT MAX(id) FROM colleges));

-- Backfill pre-existing data into the default tenant (additive).
UPDATE departments SET college_id = 1 WHERE college_id IS NULL;

UPDATE faculty f
SET college_id = COALESCE(
    (SELECT d.college_id FROM departments d
     WHERE d.id = f.department_id AND d.college_id IS NOT NULL),
    1)
WHERE f.college_id IS NULL;

UPDATE users SET college_id = 1 WHERE college_id IS NULL;

-- Every existing platform admin also becomes the root college admin.
INSERT INTO user_roles (user_id, role_id)
SELECT DISTINCT u.id, r.id
FROM users u
JOIN user_roles ur_sa      ON ur_sa.user_id = u.id
JOIN roles      sa         ON sa.id = ur_sa.role_id AND sa.name = 'ROLE_SUPER_ADMIN'
JOIN roles      r          ON r.name = 'ROLE_COLLEGE_ADMIN'
WHERE NOT EXISTS (
    SELECT 1
    FROM user_roles ur2
    JOIN roles r2 ON r2.id = ur2.role_id AND r2.name = 'ROLE_COLLEGE_ADMIN'
    WHERE ur2.user_id = u.id
);